language: java
sudo: required

cache:
  - directories:
    - .cache/oracle

before_install:
    - sudo apt-get install -y eclipse
    - sudo apt-get -qq install libaio1 rpm
    - if [ ! -f .cache/oracle/oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm ]; then .travis/oracle/download.sh; fi
    - if [ `stat -c%s .cache/oracle/oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm` -lt 5000 ]; then cat .cache/oracle/oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm && rm .cache/oracle/oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm; fi
    - sudo rpm --install --nodeps .cache/oracle/oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm

script:
    ant build.update.jar

env:
  global:
    - ORACLE_HOME=/usr/lib/oracle/12.1/client64/
    - ORACLE_DOWNLOAD_DIR=.cache/oracle
    - ORACLE_COOKIE=ic_linuxx8664
    - ORACLE_FILE='instantclient/183000/oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm'
